SayCheeseFS/saycheese

- package-lock.json
- package.json
- server/api/index.js
- server/api/product.js
> made routes for products

- server/db/models/index.js
- server/db/models/product.js
> Product model

- client/components/Product.js
- client/components/Products.js
- client/routes.js
> finished react for products

- client/routes.js
> imported products

- script/seed-data.js
- server/db/models/product.js
> Fixed product model with evaluations and seed file

- script/seed-data.js
> Fixed array issues in seed-data

- server/db/models/index.js
- server/db/models/order.js
- server/db/models/order_product.js
> created order model and associations including a through table

- client/components/auth-form.js
- client/components/navbar.js
> finished login and signup page

- client/components/Product.js
- client/routes.js
> Resolved Single Product view

- client/components/Button_Cart.js
- client/components/Product.js
- client/components/Products.js
- client/components/navbar.js
- client/routes.js
> created cart button for all products and single product pages

- client/store/cart.js
- client/store/index.js
> Cart redux

- server/api/users.js
- server/db/models/user.js
> Resolved creating a cart and user, made a change to User model

- client/store/cart.js
- client/store/index.js
- server/api/users.js
> fixed issues with cart initial state type

- server/api/users.js
> cart paths for get and put

- client/components/SingleOrder.js
- client/store/cart.js
- server/api/users.js
> fixed issues with input field on cart page

- client/store/cart.js
> Added redux part of checkout

- client/components/navbar.js
> Fixed the icon to not show when there are no items in the cart

- client/store/user.spec.js
- server/api/users.spec.js
> added test to redux and express for user profile

- client/components/user-home.spec.js
> added test for react profile page

- client/store/index.js
- client/store/order.js
- client/store/user.js
- server/api/users.js
> updated redux and express backend for profile page

- client/components/Confirmation.js
- client/components/StripeBtn.js
- client/routes.js
- server/payment/index.js
> cart checkout and confirmation fixed

- client/store/order.js
> redid order redux state

- client/components/Confirmation.js
- client/components/Products.js
- client/components/SingleOrder.js
- client/components/SingleProduct.js
> finished styling

- client/components/Confirmation.js
- client/components/OrderItem.js
- client/components/navbar.js
- client/components/user-home.spec.js
> fixed user profile

- server/api/users.js
> fixed all errors

- client/components/StripeBtn.js
- server/payment/index.js
> env variables reset

- client/components/StripeBtn.js
- server/payment/index.js
> fixing env variables
